# Generated by Django 3.1.7 on 2021-06-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210610_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='section',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='section',
            field=models.ManyToManyField(to='account.Section'),
        ),
    ]
