# Generated by Django 3.1.7 on 2021-06-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210615_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='section',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.section'),
        ),
    ]
