# Generated by Django 3.1.7 on 2021-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210616_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='xxx', max_length=255, unique=True),
        ),
    ]
