# Generated by Django 3.1.7 on 2021-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210715_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='channel',
            field=models.CharField(default='xxx', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
