# Generated by Django 3.1.7 on 2021-09-04 00:42

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210810_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to='uploads/Subject_Media', validators=[account.validators.validate_file_extension_image]),
        ),
        migrations.AlterField(
            model_name='module',
            name='module',
            field=models.FileField(upload_to='uploads/Modules', validators=[account.validators.validate_file_extension_pdf]),
        ),
    ]
