# Generated by Django 3.1.7 on 2021-09-21 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
        ('account', '0009_auto_20210810_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='assigned_subject',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subject.section'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
