# Generated by Django 3.1.7 on 2021-10-14 01:27

from django.db import migrations, models
import subject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210921_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to='uploads/', validators=[subject.validators.validate_file_extension_image]),
        ),
    ]
