# Generated by Django 3.1.7 on 2021-10-15 01:55

import account.models
from django.db import migrations, models
import subject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_studentuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to=account.models.user_directory_path, validators=[subject.validators.validate_file_extension_image]),
        ),
    ]
