# Generated by Django 3.1.7 on 2021-09-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210915_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsMultiplechoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('a', models.CharField(blank=True, max_length=255)),
                ('b', models.CharField(blank=True, max_length=255)),
                ('c', models.CharField(blank=True, max_length=255)),
                ('d', models.CharField(blank=True, max_length=255)),
                ('c_answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizMultiplchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.PositiveIntegerField()),
                ('questions', models.ManyToManyField(to='account.QuestionsMultiplechoice')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.PositiveIntegerField(default='100'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='quizmultiplchoice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.subject'),
        ),
    ]
