# Generated by Django 3.1.7 on 2021-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210916_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmultiplchoice',
            name='status',
            field=models.CharField(choices=[('hide', 'Hide'), ('show', 'Show')], default='Show', max_length=255),
        ),
    ]
