# Generated by Django 3.1.7 on 2021-09-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_quizmultiplchoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmultiplchoice',
            name='status',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Show', max_length=255),
        ),
    ]
