# Generated by Django 3.1.7 on 2021-09-21 00:48

from django.db import migrations, models
import django.db.models.deletion
import subject.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('module', models.FileField(upload_to='uploads/Modules', validators=[subject.validators.validate_file_extension_pdf])),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsMultiplechoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('a', models.CharField(blank=True, max_length=255)),
                ('b', models.CharField(blank=True, max_length=255)),
                ('c', models.CharField(blank=True, max_length=255)),
                ('d', models.CharField(blank=True, max_length=255)),
                ('c_answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('photo', models.ImageField(default='default.jpeg', upload_to='uploads/', validators=[subject.validators.validate_file_extension_image])),
                ('channel', models.CharField(default='xxx', max_length=255, unique=True)),
                ('grades', models.PositiveIntegerField(default='100')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subject.category')),
                ('modules', models.ManyToManyField(to='subject.Module')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.section')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuizMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Show', max_length=255)),
                ('date_deadline', models.DateTimeField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grades', models.PositiveIntegerField()),
                ('questions', models.ManyToManyField(to='subject.QuestionsMultiplechoice')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subject')),
            ],
        ),
    ]
