# Generated by Django 3.1.7 on 2021-10-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Hide', max_length=255)),
                ('date_deadline', models.DateTimeField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grades', models.PositiveIntegerField()),
                ('multiple_choice', models.ManyToManyField(to='subject.QuestionsMultiplechoice')),
            ],
        ),
        migrations.CreateModel(
            name='QuizParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.CharField(blank=True, max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('c_answer', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizMultipleChoice',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_paragraph',
            field=models.ManyToManyField(to='subject.QuizParagraph'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='true_false',
            field=models.ManyToManyField(to='subject.QuizTrueFalse'),
        ),
    ]
